AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with nestjs.
Resources:
  LambdaNestJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/src/lambda-entry-point.handler
      Runtime: nodejs8.10
      CodeUri: s3://ohandourabucketlamda/cf41489b39ab92f4430de88ff5d53d95
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/arrondissement
    Export:
      Name: LambdaNestApi
